"""Renders a ``live.preflight.PreflightReport`` (Phase 22).

Performs no checking of its own -- only formats what
``live.preflight.run_preflight`` already computed, matching the same
compute/format split ``validation/report.py`` and ``backtest/report.py``
already established. Two forms: plain text for the terminal
(``python -m app.cli preflight``'s own output) and Markdown for a
written record (``docs/preflight_report.md``, regenerated by that same
command).
"""

from __future__ import annotations

from pathlib import Path

from live.preflight import PreflightReport

_RULE_WIDTH = 88


def render_text_report(report: PreflightReport) -> str:
    lines = [
        "=" * _RULE_WIDTH,
        "PRE-LIVE CHECKLIST".center(_RULE_WIDTH),
        f"generated {report.generated_at.isoformat()}".center(_RULE_WIDTH),
        "=" * _RULE_WIDTH,
    ]
    for index, result in enumerate(report.results, start=1):
        label = "PASS" if result.ok else "FAIL"
        lines.append(f"[{label}] {index:2d}. {result.check.value}")
        lines.append(f"       {result.detail}")
    lines.append("-" * _RULE_WIDTH)
    if report.passed:
        lines.append("OVERALL: PASS -- all 18 conditions satisfied.")
    else:
        lines.append(
            f"OVERALL: FAIL -- {len(report.failed_checks)} of {len(report.results)} "
            "condition(s) not satisfied. Live mode remains disabled."
        )
    lines.append("=" * _RULE_WIDTH)
    return "\n".join(lines)


def render_markdown_report(report: PreflightReport) -> str:
    verdict = "PASS" if report.passed else "FAIL"
    lines = [
        "# Pre-Live Checklist Report",
        "",
        f"**Result: {verdict}**",
        "",
        f"- Generated: {report.generated_at.isoformat()}",
        f"- Conditions satisfied: {len(report.results) - len(report.failed_checks)} / "
        f"{len(report.results)}",
        "",
        "See `docs/PRE_LIVE_CHECKLIST.md` for what each condition means and how it is "
        "verified. Regenerate with `python -m app.cli preflight`.",
        "",
        "| # | Condition | Result | Detail |",
        "|---|---|---|---|",
    ]
    for index, result in enumerate(report.results, start=1):
        badge = "PASS" if result.ok else "**FAIL**"
        lines.append(
            f"| {index} | {_escape(result.check.value)} | {badge} | "
            f"{_escape(result.detail)} |"
        )
    lines.append("")
    if not report.passed:
        lines.append("## Live mode remains disabled")
        lines.append("")
        lines.append(
            "The following condition(s) must be resolved before `build_broker` will accept "
            "`preflight_confirmed=True`:"
        )
        lines.append("")
        for result in report.failed_checks:
            lines.append(f"- **{result.check.value}**: {result.detail}")
    return "\n".join(lines) + "\n"


def write_reports(report: PreflightReport, *, markdown_path: Path) -> None:
    markdown_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_path.write_text(render_markdown_report(report), encoding="utf-8")


def _escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")
